2025-06-10 11:36:12,053 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:36:29,426 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:38:52,168 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:38:52,848 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:38:52,988 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:38:53,124 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-06-10 11:39:03,141 [ERROR] Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [em C:\Users\690275\Documents\github\MeuCursoIdeal\app.py:156]
Traceback (most recent call last):
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\690275\Documents\github\MeuCursoIdeal\venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
